Repository Slicer/Slicer, pull requests merged in 2020-04, with the labels that each got.

#4800 ENH: Add interaction handles for transforming markup positions
  Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx
  Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.h
  Modules/Loadable/Markups/MRML/vtkMRMLMarkupsAngleNode.cxx
  Modules/Loadable/Markups/MRML/vtkMRMLMarkupsAngleNode.h
  Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.cxx
  Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.h
  Modules/Loadable/Markups/MRML/vtkMRMLMarkupsLineNode.cxx
  Modules/Loadable/Markups/MRML/vtkMRMLMarkupsLineNode.h
  Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.cxx
  Modules/Loadable/Markups/MRML/vtkMRMLMarkupsNode.h
  Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneNode.cxx
  Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneNode.h
  Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.cxx
  Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.h
  Modules/Loadable/Markups/Testing/Cxx/CMakeLists.txt
  Modules/Loadable/Markups/Testing/Cxx/vtkMRMLMarkupsNodeTest4.cxx
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation2D.cxx
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation2D.h
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation3D.cxx
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleRepresentation3D.h
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation2D.cxx
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation2D.h
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation3D.cxx
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerLineRepresentation3D.h
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.cxx
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidget.h
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.cxx
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation.h
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation2D.cxx
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation2D.h
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.h
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation2D.cxx
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation2D.h
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.cxx
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.h
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneWidget.cxx
  Modules/Loadable/Markups/Widgets/Resources/UI/qMRMLMarkupsDisplayNodeWidget.ui
  Modules/Loadable/Markups/Widgets/qMRMLMarkupsDisplayNodeWidget.cxx
  Modules/Loadable/Markups/Widgets/qMRMLMarkupsDisplayNodeWidget.h
Labels: type:enhancement

#4858 ENH: Hide unconfigurable BRAINSTools cmake options
  SuperBuild.cmake
Labels: priority:low, type:enhancement

#4856 BUG: Fix git hooks for git 2.18 and greater
  commit-msg
  pre-commit
Labels: priority:urgent, type:bug

#4857 Fix OpenSSL build issues on Mac 10.15 XCode 11 clean OS
  SuperBuild/External_OpenSSL.cmake
Labels: priority:medium

#4870 ENH: Make qMRMLNodeComboBox node editing easier
  Base/QTApp/qSlicerMainWindow.cxx
  Base/QTCore/qSlicerCoreApplication.cxx
  Base/QTCore/qSlicerCoreApplication.h
  Base/QTGUI/qSlicerApplication.cxx
  Base/QTGUI/qSlicerApplication.h
  Libs/MRML/Core/vtkMRMLInteractionNode.cxx
  Libs/MRML/Core/vtkMRMLInteractionNode.h
  Libs/MRML/Logic/vtkMRMLApplicationLogic.cxx
  Libs/MRML/Logic/vtkMRMLApplicationLogic.h
  Libs/MRML/Widgets/Resources/UI/qMRMLChartViewControllerWidget.ui
  Libs/MRML/Widgets/Resources/UI/qMRMLPlotViewControllerWidget.ui
  Libs/MRML/Widgets/Resources/UI/qMRMLSliceControllerWidget.ui
  Libs/MRML/Widgets/Resources/UI/qMRMLTableViewControllerWidget.ui
  Libs/MRML/Widgets/qMRMLLayoutManager.cxx
  Libs/MRML/Widgets/qMRMLNodeComboBox.cxx
  Libs/MRML/Widgets/qMRMLNodeComboBox.h
  Libs/MRML/Widgets/qMRMLNodeComboBox_p.h
  Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx
  Libs/MRML/Widgets/qMRMLSliceWidget.cxx
Labels: type:enhancement

#4890 ENH: Always use filenames that user typed in save data dialog
  Base/QTGUI/qSlicerSaveDataDialog.cxx
  Base/QTGUI/qSlicerSaveDataDialog_p.h
Labels: type:bug
