Repository Slicer/Slicer, pull requests merged in 2020-03, with the labels that each got.

#4730 COMP: Remove unused function from Tcl wrapping
  Base/QTCore/qSlicerSlicer2SceneReader.cxx
  Base/QTCore/qSlicerXcedeCatalogReader.cxx
  Libs/MRML/Core/vtkMRMLScene.cxx
  Libs/MRML/Core/vtkMRMLScene.h
Labels: bug

#4744 ENH: Replace old "scripted" module template by the new "scripteddesigner" template
  CMake/SlicerExtensionTemplatesGenerator.cmake
  Utilities/Templates/Modules/Scripted/CMakeLists.txt
  Utilities/Templates/Modules/Scripted/Resources/UI/TemplateKey.ui
  Utilities/Templates/Modules/Scripted/TemplateKey.py
  Utilities/Templates/Modules/ScriptedDesigner/CMakeLists.txt
  Utilities/Templates/Modules/ScriptedDesigner/Resources/Icons/TemplateKey.png
  Utilities/Templates/Modules/ScriptedDesigner/TemplateKey.py
  Utilities/Templates/Modules/ScriptedDesigner/Testing/CMakeLists.txt
  Utilities/Templates/Modules/ScriptedDesigner/Testing/Python/CMakeLists.txt
Labels: type:enhancement

#4747 ENH: Added Python scripted CLI module template
  Utilities/Templates/Modules/ScriptedCLI/CMakeLists.txt
  Utilities/Templates/Modules/ScriptedCLI/TemplateKey.py
  Utilities/Templates/Modules/ScriptedCLI/TemplateKey.xml
Labels: type:enhancement

#4745 Fix extension config with depends
  CMake/SlicerExtensionCPack.cmake
  Extensions/CMake/SlicerBlockAdditionalLauncherSettings.cmake
  Extensions/CMake/SlicerBlockBuildPackageAndUploadExtension.cmake
  Extensions/Testing/CLIExtensionTemplate/CMakeLists.txt
  Extensions/Testing/EditorExtensionTemplate/CMakeLists.txt
  Extensions/Testing/LoadableExtensionTemplate/CMakeLists.txt
  Extensions/Testing/ScriptedLoadableExtensionTemplate/CMakeLists.txt
  Extensions/Testing/ScriptedSegmentEditorEffectExtensionTemplate/CMakeLists.txt
  Extensions/Testing/SuperBuildExtensionTemplate/CMakeLists.txt
  Utilities/Templates/Extensions/Default/CMakeLists.txt
  Utilities/Templates/Extensions/SuperBuild/CMakeLists.txt
Labels: type:bug

#4746 ENH: Add new plane markup type
  Libs/MRML/Core/vtkMRMLNodePropertyMacros.h
  Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx
  Modules/Loadable/Markups/MRML/CMakeLists.txt
  Modules/Loadable/Markups/MRML/vtkMRMLMarkupsCurveNode.cxx
  Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.h
  Modules/Loadable/Markups/MRML/vtkMRMLMarkupsFiducialStorageNode.cxx
  Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneNode.cxx
  Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneNode.h
  Modules/Loadable/Markups/MRMLDM/vtkMRMLMarkupsDisplayableManager.cxx
  Modules/Loadable/Markups/Resources/Icons/MarkupsPlaneMouseModePlace.png
  Modules/Loadable/Markups/Resources/Icons/MarkupsPlaneMouseModePlaceAdd.png
  Modules/Loadable/Markups/Resources/UI/qSlicerMarkupsModule.ui
  Modules/Loadable/Markups/Resources/qSlicerMarkupsModule.qrc
  Modules/Loadable/Markups/SubjectHierarchyPlugins/Resources/Icons/MarkupsPlane.png
  Modules/Loadable/Markups/SubjectHierarchyPlugins/Resources/qSlicerMarkupsSubjectHierarchyPlugins.qrc
  Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.cxx
  Modules/Loadable/Markups/VTKWidgets/CMakeLists.txt
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerAngleWidget.h
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation2D.h
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation2D.cxx
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation2D.h
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.cxx
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneRepresentation3D.h
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneWidget.cxx
  Modules/Loadable/Markups/VTKWidgets/vtkSlicerPlaneWidget.h
  Modules/Loadable/Markups/qSlicerMarkupsModule.cxx
  Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx
  Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.h
Labels: type:enhancement

#4770 BUG: Fix markups cannot be placed after loading a scene
  Libs/MRML/Core/vtkMRMLSegmentationDisplayNode.cxx
  Libs/MRML/Core/vtkMRMLSelectionNode.cxx
  Libs/MRML/Core/vtkMRMLSelectionNode.h
  Libs/MRML/Core/vtkMRMLSubjectHierarchyLegacyNode.cxx
  Libs/MRML/DisplayableManager/Testing/Data/vtkMRMLCameraDisplayableManagerTest1.mrml
  Libs/MRML/Logic/vtkMRMLApplicationLogic.cxx
  Libs/vtkSegmentationCore/vtkSegment.cxx
  Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx
  Modules/Loadable/Plots/Widgets/qMRMLPlotSeriesPropertiesWidget.cxx
  Modules/Loadable/Volumes/SubjectHierarchyPlugins/qSlicerSubjectHierarchyVolumesPlugin.cxx
Labels: type:bug

#4780 BUG: Fix crash in qMRMLSceneTransformModelTest1
  Libs/MRML/Widgets/Testing/qMRMLSceneTransformModelTest1.cxx
Labels: type:bug
