Repository Slicer/Slicer, pull requests merged in 2023-08, with the labels that each got.

#7160 DOC: Copy edits to mrml_overview.md
  Docs/developer_guide/mrml_overview.md
Labels: type:documentation

#6913 DOC: Describe how pip_install can be used in a module
  Docs/developer_guide/python_faq.md
  Docs/developer_guide/script_repository/gui.md
Labels: status:in-progress

#7181 COMP: Fix extension packaging on macOS accounting for synthetic firmlink
  CMake/SlicerExtensionCPack.cmake
Labels: backport:5.x

#7204 DOC: Ensure published documentation uses "sphinx_rtd_theme"
  Docs/conf.py
Labels: type:bug, type:documentation
