Repository Slicer/Slicer, pull requests merged in 2023-09, with the labels that each got.

#7199 DOC: Add security policy document
  SECURITY.md
Labels: type:documentation

#7152 DOC: Add docs for CompareVolumes module
  Docs/user_guide/modules/comparevolumes.md
  Docs/user_guide/modules/index.md
Labels: type:documentation

#7226 BUG: Fix closed surface disappearing when segment is removed
  Libs/vtkSegmentationCore/vtkSegmentation.cxx
Labels: backport:5.x

#7243 BUG: Make more strings translatable
  Extensions/Testing/ScriptedLoadableExtensionTemplate/ScriptedLoadableModuleTemplate/ScriptedLoadableModuleTemplate.py
  Extensions/Testing/ScriptedSegmentEditorEffectExtensionTemplate/ScriptedSegmentEditorEffectModuleTemplate/SegmentEditorScriptedSegmentEditorEffectModuleTemplate.py
  Modules/Loadable/Models/qSlicerModelsModule.cxx
  Modules/Loadable/VolumeRendering/qSlicerVolumeRenderingModule.cxx
  Modules/Scripted/CropVolumeSequence/CropVolumeSequence.py
  Modules/Scripted/DMRIInstall/DMRIInstall.py
  Modules/Scripted/Endoscopy/Endoscopy.py
  Modules/Scripted/ImportItkSnapLabel/ImportItkSnapLabel.py
  Modules/Scripted/SampleData/SampleData.py
  Modules/Scripted/ScreenCapture/ScreenCapture.py
  Modules/Scripted/SegmentEditor/SegmentEditor.py
  Modules/Scripted/SelfTests/SelfTests.py
  Modules/Scripted/VectorToScalarVolume/VectorToScalarVolume.py
  Utilities/Templates/Modules/Scripted/TemplateKey.py
  Utilities/Templates/Modules/ScriptedSegmentEditorEffect/SegmentEditorTemplateKey.py
Labels: domain:i18n

#7176 ENH: Support restoring SliceViewAnnotations enabled state
  Modules/Scripted/DataProbe/DataProbeLib/SliceViewAnnotations.py
Labels: type:enhancement
