Repository Slicer/Slicer, pull requests merged in 2023-07, with the labels that each got.

#6710 COMP: Replace deprecated Qt Script usage
  Base/QTCore/Testing/Cxx/qSlicerApplicationUpdateManagerTest.cxx
  Base/QTCore/Testing/Cxx/qSlicerExtensionsManagerModelTest.cxx
  Base/QTCore/qSlicerApplicationUpdateManager.cxx
  CMakeLists.txt
  Docs/developer_guide/build_instructions/linux.md
  Docs/developer_guide/build_instructions/macos.md
  Docs/developer_guide/build_instructions/windows.md
  SuperBuild/External_qRestAPI.cmake
Labels: dependencies

#7021 Update Slicer Controller adding Thick Slab Reconstruction
  Libs/MRML/Core/Testing/vtkMRMLSliceNodeTest1.cxx
  Libs/MRML/Core/vtkMRMLSliceNode.cxx
  Libs/MRML/Core/vtkMRMLSliceNode.h
  Libs/MRML/Logic/vtkMRMLSliceLogic.cxx
  Libs/MRML/Logic/vtkMRMLSliceLogic.h
  Libs/MRML/Widgets/Resources/Icons/SlabReconstruction.png
  Libs/MRML/Widgets/Resources/UI/qMRMLSliceControllerWidget.ui
  Libs/MRML/Widgets/Resources/qMRMLWidgets.qrc
  Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx
  Libs/MRML/Widgets/qMRMLSliceControllerWidget.h
  Libs/MRML/Widgets/qMRMLSliceControllerWidget_p.h
  Modules/Scripted/DataProbe/DataProbeLib/SliceViewAnnotations.py
Labels: type:enhancement

#7046 COMP: Update python packages to latest
  SuperBuild/External_python-dicom-requirements.cmake
  SuperBuild/External_python-extension-manager-ssl-requirements.cmake
  SuperBuild/External_python-numpy.cmake
  SuperBuild/External_python-pip.cmake
  SuperBuild/External_python-pythonqt-requirements.cmake
  SuperBuild/External_python-requests-requirements.cmake
  SuperBuild/External_python-scipy.cmake
  SuperBuild/External_python-setuptools.cmake
  SuperBuild/External_python-wheel.cmake
Labels: dependencies

#7107 ENH: Allow update_translations.py to create new translation components
  Utilities/Scripts/update_translations.py
Labels: domain:i18n
