Repository Slicer/Slicer, pull requests merged in 2023-12, with the labels that each got.

#7447 BUG: Fix vtkQtTranslator leak on quick exit
  Base/QTCore/qSlicerCoreApplication.cxx
Labels: backport:5.x

#7451 ENH: Disable pip version check
  SuperBuild/External_python-pip.cmake
Labels: backport:5.x

#7309 BUG: Make more strings translatable
  Base/Python/slicer/ScriptedLoadableModule.py
  Modules/Scripted/CropVolumeSequence/CropVolumeSequence.py
  Modules/Scripted/DataProbe/DataProbe.py
  Modules/Scripted/SampleData/SampleData.py
  Modules/Scripted/SelfTests/SelfTests.py
  Modules/Scripted/WebServer/WebServer.py
Labels: Domain: i18n

#7455 BUG: Workaround for Slicer hang on scipy.linalg import on Windows 11
  Base/Python/slicer/__init__.py
Labels: backport:5.x

#7453 BUG: Update VTK to to fix vtkSMPToolsAPI static initialization order issue
  SuperBuild/External_VTK.cmake
Labels: backport:5.x

#7358 BUG: Fix context change at runtime in DICOM module
  Modules/Loadable/SubjectHierarchy/Widgets/Python/CMakeLists.txt
  Modules/Loadable/SubjectHierarchy/Widgets/Python/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py
  Modules/Loadable/SubjectHierarchy/Widgets/Python/SubjectHierarchyPlugins/__init__.py
  Modules/Scripted/SegmentEditor/SubjectHierarchyPlugins/__init__.py
  Modules/Scripted/SegmentStatistics/SubjectHierarchyPlugins/__init__.py
Labels: Domain: i18n, Domain: DICOM

#7507 BUG: Update VTK backporting OpenVR rendering fix when HMD inside the volume
  SuperBuild/External_VTK.cmake
Labels: backport:5.x

#7501 DOC: Clarify when local build is needed for extension development
  Docs/developer_guide/extensions.md
Labels: backport:5.x
