Repository Slicer/Slicer, pull requests merged in 2023-11, with the labels that each got.

#7336 ENH: Remove FreeSurfer file extensions from qSlicerModelsReader
  Modules/Loadable/Models/qSlicerModelsReader.cxx
Labels: backport:5.x

#7362 ENH: Support regularization transform hardening in DICOM Scalar plugin
  Docs/user_guide/modules/dicom.md
  Modules/Scripted/DICOMPlugins/DICOMScalarVolumePlugin.py
Labels: Type: Enhancement, Domain: DICOM

#7306 BUG: Fix parameter node wrapper observers not being removed
  Base/Python/slicer/parameterNodeWrapper/wrapper.py
Labels: Type: Bug

#7371 DOC: Add instructions for setting up development environment on Ubuntu 23.04
  Docs/developer_guide/build_instructions/linux.md
Labels: Type: Documentation

#7396 COMP: Fix reporting of -Wunused-function related to qSlicerApplicationHelper
  Base/QTApp/qSlicerApplicationHelper.txx
Labels: Type: Bug, Domain: build-system

#7404 ENH: Make sequence item creating strategy configurable
  Modules/Loadable/Sequences/Logic/vtkSlicerSequencesLogic.cxx
  Modules/Loadable/Sequences/MRML/vtkMRMLSequenceBrowserNode.cxx
  Modules/Loadable/Sequences/MRML/vtkMRMLSequenceBrowserNode.h
  Modules/Loadable/Sequences/Testing/Cxx/CMakeLists.txt
  Modules/Loadable/Sequences/Testing/Cxx/vtkSlicerSequencesLogicTest1.cxx
Labels: Type: Enhancement

#7165 ENH: Endoscopy fly through with user's camera transforms
  Docs/user_guide/modules/endoscopy.md
  Modules/Scripted/Endoscopy/Endoscopy.py
Labels: Type: Enhancement

#7430 BUG: Fix temporary folder containing special characters
  Base/Python/slicer/util.py
  Base/QTGUI/qSlicerApplication.cxx
  Modules/Scripted/DICOMLib/DICOMUtils.py
  Modules/Scripted/DICOMLib/Widgets/qSlicerDICOMExportDialog.cxx
Labels: Type: Bug, Domain: i18n, backport:5.x
