Repository Slicer/Slicer, pull requests merged in 2025-07, with the labels that each got.

#8519 ENH: Make JSON files in extensions translatable
  Modules/Loadable/Volumes/Logic/vtkSlicerVolumesLogic.cxx
  Modules/Loadable/Volumes/Resources/Schema/volumes-display-presets-schema-v1.0.1.json
  Modules/Loadable/Volumes/Resources/VolumeDisplayPresets.json
  Utilities/Scripts/update_translations.py
Labels: Domain: i18n

#8577 COMP: Ensure `isPythonDisabled` is defined regardless of Python support
  Base/QTCore/qSlicerCoreCommandOptions.cxx
  Base/QTCore/qSlicerCoreCommandOptions.h
Labels: Priority: Medium

#6708 COMP: Switch from zlib 1.2.3 to maintained zlib-ng 2.2.4 fork
  SuperBuild/External_zlib.cmake
Labels: dependencies
